language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - server/node_modules
    - client/node_modules
script:
  - cd client && npm i && npm run travis:test && cd ../server && npm i && npm run travis:test
